version: '3'

services:
  database:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: "temp"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "sauron"
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/v0001_init.sql:/docker-entrypoint-initdb.d/v0001_init.sql
