version: '3'

services:
  database:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: temp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sauron
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d temp"]
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/v0001_init.sql:/docker-entrypoint-initdb.d/v0001_init.sql
  classification-api:
      image: murilokakazu/sauroniiot-classification-api
      ports:
        - "8083:8083"
      environment:
        PROD: "True"
        MODEL_PATH: /app/model/weights/model.h5
      volumes:
        - ./captures:/app/captures
  sauron-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      ENV_FOR_DYNACONF: "dev"
    ports:
      - "5000:5000"
    depends_on: 
      - database
      - classification-api
    command: [
      ".bin/wait-for-it.sh", "database:5432", "--", 
      ".bin/wait-for-it.sh", "classification-api:8083", "--", 
      "python", "api.py"]
    volumes:
      - ./captures:/captures
      - ~/.aws/:/root/.aws:ro
    tty: true
  worker-upload:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      SAURON_WORKER_NAME: "upload"
      SAURON_WORKER_SLEEP: 15
      ENV_FOR_DYNACONF: "dev"
    depends_on: 
      - database
      - classification-api
      - sauron-api
    command: [
      ".bin/wait-for-it.sh", "database:5432", "--", 
      ".bin/wait-for-it.sh", "classification-api:8083", "--", 
      "python", "worker.py"]
    volumes:
      - ./captures:/captures
      - ~/.aws/:/root/.aws:ro
    tty: true
  worker-cleanup:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      SAURON_WORKER_NAME: "cleanup"
      SAURON_WORKER_SLEEP: 30
      ENV_FOR_DYNACONF: "dev"
    depends_on: 
      - database
      - classification-api
      - sauron-api
    command: [
      ".bin/wait-for-it.sh", "database:5432", "--", 
      ".bin/wait-for-it.sh", "classification-api:8083", "--", 
      "python", "worker.py"]
    volumes:
      - ./captures:/captures
      - ~/.aws/:/root/.aws:ro
    tty: true