[default]
application_name = 'sauron'

[dev]
broker_address = "http://52.67.64.156:1026"
camera_address = "http://192.168.0.243/capture"
classification_address = "http://classification-api:8083"
s3_bucket = "ftt-iiot-sauron"

[prod]
